src/Limitless/KarhabtiBundle/Entity/Vehicule.php
<?php

namespace Limitless\KarhabtiBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 */
class Vehicule
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string",length=255, nullable=false, unique=true)
     */
    private $matricule;
    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $reserved=false;

    /**
     * @Assert\File(maxSize="6000k")
     */
    public $file;
    /**
     * @var \DateTime
     * @ORM\Column(name="dExp_assurance",type="date", nullable=false)
     */
    private $date_expiration_assurance;
    /**
     * @var \DateTime
     * @ORM\Column(name="dExp_vignette",type="date", nullable=false)
     */
    private $date_expiration_vignette;
    /**
     * @var \DateTime
     * @ORM\Column(name="dExp_visite",type="date", nullable=false)
     */
    private $date_expiration_visite;
    /**
     * @ORM\ManyToOne(targetEntity="Marque")
     * @ORM\JoinColumn(name="marque_id",referencedColumnName="id")
     */
    private $marque;
    /**
     * @ORM\ManyToOne(targetEntity="Modele")
     * @ORM\JoinColumn(name="modele_id",referencedColumnName="id")
     */
    private $modele;
    /**
     * @ORM\ManyToOne(targetEntity="TypeV")
     * @ORM\JoinColumn(name="typeV_id",referencedColumnName="id")
     */
    private $typeV;
    /**
     * @ORM\ManyToOne(targetEntity="Agence")
     * @ORM\JoinColumn(name="agence_id",referencedColumnName="id")
     */
    private $agence;

    /**
     * @return mixed
     */
    public function getReserved()
    {
        return $this->reserved;
    }

    /**
     * @param mixed $reserved
     */
    public function setReserved($reserved)
    {
        $this->reserved = $reserved;
    }



    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getMatricule()
    {
        return $this->matricule;
    }

    /**
     * @param mixed $matricule
     */
    public function setMatricule($matricule)
    {
        $this->matricule = $matricule;
    }



    /**
     * @return \DateTime
     */
    public function getDateExpirationAssurance()
    {
        return $this->date_expiration_assurance;
    }

    /**
     * @param \DateTime $date_expiration_assurance
     */
    public function setDateExpirationAssurance($date_expiration_assurance)
    {
        $this->date_expiration_assurance = $date_expiration_assurance;
    }

    /**
     * @return \DateTime
     */
    public function getDateExpirationVignette()
    {
        return $this->date_expiration_vignette;
    }

    /**
     * @param \DateTime $date_expiration_vignette
     */
    public function setDateExpirationVignette($date_expiration_vignette)
    {
        $this->date_expiration_vignette = $date_expiration_vignette;
    }

    /**
     * @return \DateTime
     */
    public function getDateExpirationVisite()
    {
        return $this->date_expiration_visite;
    }

    /**
     * @param \DateTime $date_expiration_visite
     */
    public function setDateExpirationVisite($date_expiration_visite)
    {
        $this->date_expiration_visite = $date_expiration_visite;
    }

    /**
     * @return mixed
     */
    public function getMarque()
    {
        return $this->marque;
    }

    /**
     * @param mixed $marque
     */
    public function setMarque($marque)
    {
        $this->marque = $marque;
    }

    /**
     * @return mixed
     */
    public function getTypeV()
    {
        return $this->typeV;
    }

    /**
     * @param mixed $typeV
     */
    public function setTypeV($typeV)
    {
        $this->typeV = $typeV;
    }

    /**
     * @return mixed
     */
    public function getModele()
    {
        return $this->modele;
    }

    /**
     * @param mixed $modele
     */
    public function setModele($modele)
    {
        $this->modele = $modele;
    }

    /**
     * @return mixed
     */
    public function getAgence()
    {
        return $this->agence;
    }

    /**
     * @param mixed $agence
     */
    public function setAgence($agence)
    {
        $this->agence = $agence;
    }


    function __toString()
    {
        return $this->getMatricule();
    }


}

src/Limitless/KarhabtiBundle/Form/VehiculeType.php
<?php

namespace Limitless\KarhabtiBundle\Form;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VehiculeType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('matricule')
            ->add('file',FileType::class, array(
                    'multiple'    => false,
                    'attr' => array(

                        'accept' => 'image/*',
                    )
                )
            )
            ->add('date_expiration_assurance',DateType::class , array( 'widget' =>
                'single_text', 'format' => 'dd-MM-yyyy','attr' =>
                array('class' => 'input','data-provide' =>
                    'datepicker','data-date-format' => 'dd-mm-yyyy')))
            ->add('date_expiration_vignette',DateType::class , array( 'widget' =>
                'single_text', 'format' => 'dd-MM-yyyy','attr' =>
                array('class' => 'input','data-provide' =>
                    'datepicker','data-date-format' => 'dd-mm-yyyy')))
            ->add('date_expiration_visite',DateType::class , array( 'widget' =>
                'single_text', 'format' => 'dd-MM-yyyy','attr' =>
                array('class' => 'input','data-provide' =>
                    'datepicker','data-date-format' => 'dd-mm-yyyy')))
            ->add('marque')
            ->add('modele')
            ->add('typeV')        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Limitless\KarhabtiBundle\Entity\Vehicule'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'limitless_karhabtibundle_vehicule';
    }


}

src/Limitless/KarhabtiBundle/Controller/VehiculeController.php
<?php

namespace Limitless\KarhabtiBundle\Controller;

use Limitless\KarhabtiBundle\Entity\Vehicule;
use Limitless\KarhabtiBundle\LimitlessKarhabtiBundle;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Vehicule controller.
 *
 */
class VehiculeController extends Controller
{
    /**
     * Lists all vehicule entities.
     *
     */


    /**
     * Creates a new vehicule entity.
     *
     */
    public function newAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $profil=  $em->getRepository('LimitlessKarhabtiBundle:Agence')->findOneBy(array('user' => $user));

        $vehicule = new Vehicule();
        $form = $this->createForm('Limitless\KarhabtiBundle\Form\VehiculeType', $vehicule);
        $form->handleRequest($request);
        $err1="";
        $err2="";
        $err3="";
        if ($form->isSubmitted()) {
            if($vehicule->getDateExpirationAssurance()<(new \DateTime('now'))) {
                $err1="Date Expiration Assurance doit etre supperieur à la date du jour";
            }elseif ($vehicule->getDateExpirationVignette()<(new \DateTime('now'))) {
                $err2="Date Expiration Vignette doit etre supperieur à la date du jour";
            }elseif ($vehicule->getDateExpirationVisite()<(new \DateTime('now'))) {
                $err3="Date Expiration Visite doit etre supperieur à la date du jour";
            }else{
            $em = $this->getDoctrine()->getManager();
            $image= $form['file']->getData();

            $req = $request->request->get('limitless_karhabtibundle_vehicule');
            $id=$req['matricule'];

                $modele=$req['modele'];
                $modele=$em->getRepository('LimitlessKarhabtiBundle:Modele')->findOneBy(array("libelleMo"=>$modele));
                $vehicule->setModele($modele);
                $marque=$req['marque'];
                $marque=$em->getRepository('LimitlessKarhabtiBundle:Marque')->findOneBy(array("libelleMa"=>$marque));
                $vehicule->setMarque($marque);
                $vehicule->setAgence($profil);


                if(!is_dir("bundles/limitlesskarhabti/Image/Vehicule")){
                    mkdir("bundles/limitlesskarhabti/Image/Vehicule");

                }

                mkdir("bundles/limitlesskarhabti/Image/Vehicule/".$id);
                move_uploaded_file ($image,"bundles/limitlesskarhabti/Image/Vehicule/".$id."/".$image->getFileName());
                rename("bundles/limitlesskarhabti/Image/Vehicule/".$id."/".$image->getFileName(), "bundles/limitlesskarhabti/Image/Vehicule/".$id."/".$id.".jpg");



            $em->persist($vehicule);
            $em->flush();

            return $this->redirectToRoute('responsable_vehicule_index', array('id' => $vehicule->getId()));
            }

            }


        return $this->render('LimitlessKarhabtiBundle:Vehicule:ajouter.html.twig', array(
            'vehicule' => $vehicule,
            'err1' => $err1,
            'err2' => $err2,
            'err3' => $err3,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a vehicule entity.
     *
     */
    public function showAction(Vehicule $vehicule)
    {

        $deleteForm = $this->createDeleteForm($vehicule);

        return $this->render('@LimitlessKarhabti/Vehicule/show.html.twig', array(
            'vehicule' => $vehicule,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing vehicule entity.
     *
     */
    public function editAction(Request $request, Vehicule $vehicule)
    {
        $deleteForm = $this->createDeleteForm($vehicule);
        $editForm = $this->createForm('Limitless\KarhabtiBundle\Form\VehiculeType', $vehicule);
        $editForm->handleRequest($request);
        $err1="";
        $err2="";
        $err3="";

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            if($vehicule->getDateExpirationAssurance()<(new \DateTime('now'))) {
                $err1="Date Expiration Assurance doit etre supperieur à la date du jour";
            }elseif ($vehicule->getDateExpirationVignette()<(new \DateTime('now'))) {
                $err2="Date Expiration Vignette doit etre supperieur à la date du jour";
            }elseif ($vehicule->getDateExpirationVisite()<(new \DateTime('now'))) {
                $err3="Date Expiration Visite doit etre supperieur à la date du jour";
            }else {
                $em = $this->getDoctrine()->getManager();
                $image= $editForm['file']->getData();

                $req = $request->request->get('limitless_karhabtibundle_vehicule');
                $id=$req['matricule'];
                if(!is_dir("bundles/limitlesskarhabti/Image/Vehicule")){
                    mkdir("bundles/limitlesskarhabti/Image/Vehicule");

                }

                mkdir("bundles/limitlesskarhabti/Image/Vehicule/".$id);
                move_uploaded_file ($image,"bundles/limitlesskarhabti/Image/Vehicule/".$id."/".$image->getFileName());
                rename("bundles/limitlesskarhabti/Image/Vehicule/".$id."/".$image->getFileName(), "bundles/limitlesskarhabti/Image/Vehicule/".$id."/".$id.".jpg");

                $this->getDoctrine()->getManager()->flush();

                return $this->redirectToRoute('responsable_vehicule_index', array('id' => $vehicule->getId()));
            }
        }

        return $this->render('LimitlessKarhabtiBundle:Vehicule:modifier.html.twig', array(
            'vehicule' => $vehicule,
            'err1' => $err1,
            'err2' => $err2,
            'err3' => $err3,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a vehicule entity.
     *
     */
    public function deleteAction(Request $request, Vehicule $vehicule)
    {
        $form = $this->createDeleteForm($vehicule);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($vehicule);
            $em->flush($vehicule);
        }

        return $this->redirectToRoute('responsable_vehicule_index');
    }

    /**
     * Creates a form to delete a vehicule entity.
     *
     * @param Vehicule $vehicule The vehicule entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Vehicule $vehicule)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('responsable_vehicule_delete', array('id' => $vehicule->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }
  public function deleteidAction( $id)
    {

            $em = $this->getDoctrine()->getManager();
        $vehicule=$em->getRepository('LimitlessKarhabtiBundle:Vehicule')->findOneBy(array("id"=>$id));
        $taches=$em->getRepository('LimitlessKarhabtiBundle:Tache')->findBy(array("vehicule"=>$vehicule));

            for($j=0;$j<count($taches);$j++){

                $taches[$j]->setVehicule(null);

                $em->persist($taches[$j]);
                $em->flush();
            }



            $em->remove($vehicule);
            $em->flush();


        return $this->redirectToRoute('responsable_vehicule_index');
    }

    public function rechercheAction(Request $Request){

        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $profil=  $em->getRepository('LimitlessKarhabtiBundle:Agence')->findOneBy(array('user' => $user));

        $vehicule=  $em->getRepository('LimitlessKarhabtiBundle:Vehicule')->findBy(array('agence' => $profil));

        if($Request->isMethod('POST'))

        {
            $search=$Request->get('matricule');
            $vehicule=$em->getRepository('LimitlessKarhabtiBundle:Vehicule')->findBy(array("matricule"=>$search,'agence' => $profil));

        }elseif ($Request->isMethod('POST')){
            $search=$Request->get('typeV');
            $vehicule=$em->getRepository('LimitlessKarhabtiBundle:Vehicule')->findBy(array("typeV"=>$search));
        }

        return $this->render('LimitlessKarhabtiBundle:Vehicule:list.html.twig',
            array(
                "vehicule"=>$vehicule,
            'user' => $profil,));



    }









}

src/Limitless/KarhabtiBundle/Resources/views/Vehicule/list.html.twig
{% extends "LimitlessKarhabtiBundle::layout.html.twig" %}
{% block title %}
    {{ parent() }}
{% endblock %}
{% block body%}
    {% set myVal = 0 %}
    {% for vehicule in vehicule %}
        {% set difference = date(vehicule.dateExpirationAssurance).diff(date('now'))   %}
        {% set leftDays = difference.days %}

        {% set difference1 = date(vehicule.dateExpirationVisite).diff(date('now'))   %}
        {% set leftDays1 = difference1.days %}

        {% set difference2 = date(vehicule.dateExpirationVignette).diff(date('now'))   %}
        {% set leftDays2 = difference2.days %}

        {% if (leftDays <= 5) or (leftDays1<= 5) or (leftDays2<= 5) %}
            {% set myVal = myVal + 1 %}
            {% endif %}


            {% endfor %}
    <!-- Header 1
 ============================================ -->
    <div class="header-area header-absolute header-transparent">
        <div class="header-bottom-2 sticky">
            <div class="container">
                <div class="row">
                    <!-- Header Bottom -->
                    <div class="col-xs-12">
                        <div class="navbar-header">
                            <a href="{{ path('limitless_karhabti_homepage') }}" class="logo navbar-brand"><img id="logo_img" src="{{ asset('bundles/limitlesskarhabti/img/logo/color-1.png')}}" alt="logo" /></a>
                        </div>
                        <div class="main-menu menu-style-6 mean-menu float-right">
                            <nav>
                                <ul>
                                    <li ><a href="{{ path('limitless_karhabti_homepage') }}">home</a></li>
                                    <li><a href="#">Profil</a></li>
                                    <li><a href="#">Offre/Pack<i class="icofont icofont-simple-down"></i></a>
                                        <ul>
                                            <li><a href="{{ path('responsable_offre_index') }}">Offre</a></li>
                                            <li><a href="{{ path('responsable_pack_index') }}">Pack</a></li>
                                        </ul>
                                    </li>
                                    {% if myVal >0 %}
                                    <li class="active"><a href="{{ path('responsable_vehicule_index') }}">Vehicule  ({{ myVal }})</a></li>
                                        {% else %}
                                            <li class="active"><a href="{{ path('responsable_vehicule_index') }}">Vehicule</a></li>
                                            {% endif %}
                                    <li><a href="#">Moniteur</a></li>
                                    <li><a href="{{ path('reponsable_tache_index') }}">Planning</a></li>
                                    <li><a href="#">Cour/Examen<i class="icofont icofont-simple-down"></i></a>
                                        <ul>
                                            <li><a href="{{ path('responsable_cours_List') }}">Cour</a></li>
                                            <li><a href="{{ path('responsable_examen_Liste') }}">Examen</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{{ path('limitless_karhabti_mail') }}">contact</a></li>
                                </ul>
                            </nav>
                        </div>
                        <div class="mobile-menu"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Banner -->
    <div class="page-banner-area overlay overlay-black overlay-70">
        <div class="container">
            <div class="row">
                <div class="page-banner text-center col-xs-12">
                    <h1>Responsable Auto école</h1>

                </div>
            </div>
        </div>
    </div>

    <div class="blog-area bg-white pt-90 pb-90">
        <div class="container">
            <!-- Section Title -->
            <div class="row">
                <div class="section-title text-center col-xs-12 mb-45">
                    <h3 class="heading">Liste des Vehicules</h3>

                    <i class="icofont icofont-traffic-light"></i>
                </div>
            </div>
            <div class="row">
                <style type="text/css">
                    /*Table Style - This is what you want*/
                    button {
                        background-color: #dec839; /* Green */
                        border: 1px solid #dec839;
                        color: white;
                        padding: 0px 0px;
                        text-align: center;
                        text-decoration: none;
                        font-size: 16px;
                        display: inline-block;
                        width: auto;
                        line-height: 30px;
                    }

                </style>

                <ul>
                    <li style="text-align: center">
                       <button><a  class="btn color "  href="{{ path('responsable_vehicule_new') }}">créer un nouveau vehicule</a></button>
                    </li>
                </ul>

                <form method="POST" style="padding-bottom: 2%;padding-top: 2%;padding-left: 1.7%">
                    <h3>Rechercher : <input  placeholder="Matricule" type="text" name="matricule">
                    <input  type="submit" value="Recherche"></h3>
                </form>
            {% if myVal>0 %}
            <h4 style="color: red;text-align: center">Vous avez {{ myVal }} véhicule(s) où la date d'expiration de (Assurance, Vignette ou Visite) qui va expirer bientôt !!!</h4>
            {% endif %}
                {% for vehicule in vehicule %}
                <div id="offre">

                    <div class="col-md-4" >

                <div class="thumbnail" align="center" style="background-color: ghostwhite">

                    <h1 style="color: #efe24b"><a style="text-transform: uppercase;" href="{{ path('responsable_vehicule_show', { 'id': vehicule.id }) }}"> <b>{{ vehicule.matricule }}</b></a><br></h1>

                    <label>Type Vehicule : </label>{{ vehicule.typeV }} <br>
                    <label>Marque :</label> {{ vehicule.marque }} <br>
                    <label>Modele :</label> {{ vehicule.modele }}<br>


                    {% set difference = date(vehicule.dateExpirationAssurance).diff(date('now'))   %}
                    {% set leftDays = difference.days %}

                    {% if leftDays <= 5 %}
                        {% set myVal = myVal + 1 %}

                        <label>Date d'expiration de l'assurance :</label>
                        <h5 style="color: red">Assurance Expirera bientôt !!</h5>
                            {% if vehicule.dateExpirationAssurance %}{{ vehicule.dateExpirationAssurance|date('Y-m-d') }}{% endif %}

                    {% else %}
                        <label>Date d'expiration de l'assurance :</label>
                        <h5 style="color: ghostwhite">fdsfdsf</h5>
                            {% if vehicule.dateExpirationAssurance %}{{ vehicule.dateExpirationAssurance|date('Y-m-d') }}{% endif %}

                    {% endif %}
                    <br>


                    {% set difference = date(vehicule.dateExpirationVignette).diff(date('now'))   %}
                    {% set leftDays = difference.days %}

                    {% if leftDays <= 5 %}
                        {% set myVal = myVal + 1 %}
                        <label>Date d'expiration de la vignette :</label>
                        <h5 style="color: red">Vignette Expirera bientôt !!</h5>



                            {% if vehicule.dateExpirationVignette %}{{ vehicule.dateExpirationVignette|date('Y-m-d') }}{% endif %}

                    {% else %}
                        <label>Date d'expiration de la vignette :</label>
                        <h5 style="color: ghostwhite">fdsfdsf</h5>

                            {% if vehicule.dateExpirationVignette %}{{ vehicule.dateExpirationVignette|date('Y-m-d') }}{% endif %}

                    {% endif %}
                    <br>


                    {% set difference = date(vehicule.dateExpirationVisite).diff(date('now'))   %}
                    {% set leftDays = difference.days %}

                    {% if leftDays <= 5 %}
                        {% set myVal = myVal + 1 %}
                        <label>Date d'expiration de la visite :</label>
                        <h5 style="color: red">Vignette Expirera bientôt !!</h5>



                            {% if vehicule.dateExpirationVisite %}{{ vehicule.dateExpirationVisite|date('Y-m-d') }}{% endif %}

                    {% else %}
                        <label>Date d'expiration de la visite :</label>
                        <h5 style="color: ghostwhite">fdsfdsf</h5>

                            {% if vehicule.dateExpirationVisite %}{{ vehicule.dateExpirationVisite|date('Y-m-d') }}{% endif %}

                    {% endif %}
                    <br>





                    <button style="margin-bottom: 2%;margin-top: 2%" >
                        <a  class="btn color " href="{{ path('responsable_vehicule_show', { 'id': vehicule.id }) }}">Voir les details de la voiture</a>
                    </button>
                </div>
                        </div>
                    </div>
            {% endfor %}

            </div>

        </div>
    </div>
{% endblock %}

src/Limitless/KarhabtiBundle/Resources/views/Vehicule/show.html.twig
{% extends "LimitlessKarhabtiBundle::layout.html.twig" %}
{% block title %}
    {{ parent() }}
{% endblock %}
{% block body%}
    <!-- Header 1
 ============================================ -->
    <div class="header-area header-absolute header-transparent">
        <div class="header-bottom-2 sticky">
            <div class="container">
                <div class="row">
                    <!-- Header Bottom -->
                    <div class="col-xs-12">
                        <div class="navbar-header">
                            <a href="{{ path('limitless_karhabti_homepage') }}" class="logo navbar-brand"><img id="logo_img" src="{{ asset('bundles/limitlesskarhabti/img/logo/color-1.png')}}" alt="logo" /></a>
                        </div>
                        <div class="main-menu menu-style-6 mean-menu float-right">
                            <nav>
                                <ul>
                                    <li ><a href="{{ path('limitless_karhabti_homepage') }}">home</a></li>
                                    <li><a href="#">Profil</a></li>
                                    <li><a href="#">Offre/Pack<i class="icofont icofont-simple-down"></i></a>
                                        <ul>
                                            <li><a href="{{ path('responsable_offre_index') }}">Offre</a></li>
                                            <li><a href="{{ path('responsable_pack_index') }}">Pack</a></li>
                                        </ul>
                                    </li>
                                    <li class="active"><a href="{{ path('responsable_vehicule_index') }}">Vehicule</a></li>
                                    <li><a href="#">Moniteur</a></li>
                                    <li><a href="{{ path('reponsable_tache_index') }}">Planning</a></li>
                                    <li><a href="#">Cour/Examen<i class="icofont icofont-simple-down"></i></a>
                                        <ul>
                                            <li><a href="{{ path('responsable_cours_List') }}">Cour</a></li>
                                            <li><a href="{{ path('responsable_examen_Liste') }}">Examen</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{{ path('limitless_karhabti_mail') }}">contact</a></li>
                                </ul>
                            </nav>
                        </div>
                        <div class="mobile-menu"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Banner -->
    <div class="page-banner-area overlay overlay-black overlay-70">
        <div class="container">
            <div class="row">
                <div class="page-banner text-center col-xs-12">
                    <h1>Responsable Auto école</h1>

                </div>
            </div>
        </div>
    </div>



    <!-- Gallery Area
============================================ -->
    <style type="text/css">
        button {
            background-color: #dec839; /* Green */
            border: 1px solid #dec839;
            color: white;
            padding: 0px 0px;
            text-decoration: none;
            font-size: 16px;
            display: inline-block;
            width: auto;
            line-height: 30px;
        }
    </style>

    <div style="padding-top: 5%;" class="blog-area bg-white pt-90 pb-90">


        <div class="container">
            <!-- Gallery Grid -->


            <div class="row">
                <div class="blog-wrapper float-right col-md-8 col-xs-12">

                    <div style="padding-top: 10%;" class="single-blog">

                        <h4 class="blog-title">{{ vehicule.modele }}, {{ vehicule.marque }}</h4>
                        <div class="blog-meta fix">
                            <p class="float-left">{{ vehicule.matricule }}</p>
                            <p class="float-right">
                                <button><a class="btn color" href="{{ path('responsable_vehicule_edit', { 'id': vehicule.id }) }}">Modifier</a></button>
                                <button><a class="btn color" href="{{ path('responsable_vehicule_deleteid',{id:vehicule.id}) }}">Supprimer</a></button>
                            </p>
                        </div>
                        <div class="blog-description">
                            <p>Cette vehicule est un(e) {{ vehicule.typeV }}. Elle est de modele {{ vehicule.modele }}.<br>
                                Sa date d'expiration de la vignette :</p>
                            <blockquote>
                                <ul>
                                    <li>{% if vehicule.dateexpirationassurance %}{{ vehicule.dateexpirationassurance|date('Y-m-d') }}{% endif %}</li>
                                </ul>
                            </blockquote>
                            <p>Sa date d'expiration de l'assurance :</p>
                            <blockquote>
                                <ul>
                                    <li>{% if vehicule.dateExpirationVignette %}{{ vehicule.dateExpirationVignette|date('Y-m-d') }}{% endif %}</li>
                                </ul>
                            </blockquote>
                            <p>Sa date d'expiration de la visite technique :</p>
                            <blockquote>
                                <ul>
                                    <li>{% if vehicule.dateExpirationVisite %}{{ vehicule.dateExpirationVisite|date('Y-m-d') }}{% endif %}</li>
                                </ul>
                            </blockquote>
                        </div>
                    </div>

                </div>
                <div class="sidebar col-md-4 col-xs-12">

                    <div class="blog-image" >
                        <ul>
                            <li style="text-align: left">
                                <button><a  class="btn color "  href="{{ path('responsable_vehicule_index') }}">Retour à la Liste</a></button>
                            </li>
                        </ul>
                        <img   src="{{ asset('bundles/limitlesskarhabti/Image/Vehicule/'~vehicule.matricule~'/'~vehicule.matricule~'.jpg') }}" alt="" />
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}