src/Limitless/KarhabtiBundle/Entity/Agence.php
<?php
/**
 * Created by PhpStorm.
 * User: WALA
 * Date: 05/02/2017
 * Time: 00:20
 */

namespace Limitless\KarhabtiBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 */


class Agence
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255, nullable=false)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="ville", type="string", length=255, nullable=false)
     */

    private $ville;
    /**
     * @var string
     *
     * @ORM\Column(name="adresse", type="string", length=255, nullable=false)
     */
    private $adresse;

    /**
     * @var string
     *
     * @ORM\Column(name="code_postal", type="integer", nullable=false)
     */
    private $code_postal;

    /**
     * @var string
     *
     * @ORM\Column(name="telephone", type="string", length=255, nullable=false)
     */
    private $telephone;

    /**
     * @var string
     *
     * @ORM\Column(name="num_fiscal", type="string", length=255, nullable=false)
     */

    private $num_fiscal;
    /**
     * @ORM\Column(name="Ouverture", type="string")
     */

    private $Ouverture;

    /**
     * @ORM\Column(name="Fermeture", type="string")
     */

    private $Fermeture;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="user_id",referencedColumnName="id")
     */
    private $user;

    /**
     * @Assert\File(maxSize="6000k")
     */
    public $file;


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * @param string $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }

    /**
     * @return string
     */
    public function getVille()
    {
        return $this->ville;
    }

    /**
     * @param string $ville
     */
    public function setVille($ville)
    {
        $this->ville = $ville;
    }

    /**
     * @return string
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * @param string $adresse
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;
    }

    /**
     * @return string
     */
    public function getCodePostal()
    {
        return $this->code_postal;
    }

    /**
     * @param string $code_postal
     */
    public function setCodePostal($code_postal)
    {
        $this->code_postal = $code_postal;
    }

    /**
     * @return string
     */
    public function getTelephone()
    {
        return $this->telephone;
    }

    /**
     * @param string $telephone
     */
    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;
    }

    /**
     * @return string
     */
    public function getNumFiscal()
    {
        return $this->num_fiscal;
    }

    /**
     * @param string $num_fiscal
     */
    public function setNumFiscal($num_fiscal)
    {
        $this->num_fiscal = $num_fiscal;
    }

    /**
     * @return mixed
     */
    public function getOuverture()
    {
        return $this->Ouverture;
    }

    /**
     * @param mixed $Ouverture
     */
    public function setOuverture($Ouverture)
    {
        $this->Ouverture = $Ouverture;
    }

    /**
     * @return mixed
     */
    public function getFermeture()
    {
        return $this->Fermeture;
    }

    /**
     * @param mixed $Fermeture
     */
    public function setFermeture($Fermeture)
    {
        $this->Fermeture = $Fermeture;
    }

    /**
     * @return mixed
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param mixed $user
     */
    public function setUser($user)
    {
        $this->user = $user;
    }

}

src/Limitless/KarhabtiBundle/Form/AgenceType.php
<?php

namespace Limitless\KarhabtiBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;


class AgenceType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('nom')
            ->add('ville', ChoiceType::class, array(
                'choices' => array(

                    'Tunis' => 'Tunis',
                    'Ariana' => 'Ariana',
                    'Mannouba' => 'Mannouba',
                    'Sfax' => 'Sfax',
                    'Kairouan' => 'Kairouan',
                    'Sousse' => 'Sousse',
                    'Monastir' => 'Monastir',
                    'Nabeul' => 'Nabeul',
                    'Tozeur' => 'Tozeur',
                    'Gabès' => 'Gabès',
                    'Le Kef' => 'Le Kef',
                    'Mednine' => 'Mednine',
                    'Kbeli' => 'Kbeli',
                    'Gafssa' => 'Gafssa',
                    'Gassrine' => 'Gassrine',
                    'Sidi Bouzid' => 'Sidi Bouzid',
                    'Siliana' => 'Siliana',
                    'Jandouba' => 'Jandouba',
                    'Beja' => 'Beja',
                    'Bizert' => 'Bizert ',
                    'Mahdia' => 'Mahdia',
                    'Ben arous' => 'Ben arous',
                    'Zagwen' => 'Zagwen',
                    'Tataouine' => 'Tataouine',


                )))
            ->add('adresse')
            ->add('code_postal')
            ->add('telephone')
            ->add('num_fiscal')
            ->add('file',FileType::class, array(
                    'multiple'    => false,
                    'attr' => array(

                        'accept' => 'image/*',
                    )
                )
            )
            ->add('Ouverture', ChoiceType::class, array(
                'choices' => array(
                    'Lundi' => 'Lundi',
                    'Mardi' => 'Mardi',
                    'Mercredi' => 'Mercredi',
                    'Jeudi' => 'Jeudi',
                    'Vendredi' => 'Vendredi',
                    'Samedi' => 'Samedi'
                ), 'placeholder' => 'Ouvre le') )
            ->add('Fermeture', ChoiceType::class, array(
        'choices' => array(
            'Lundi' => 'Lundi',
            'Mardi' => 'Mardi',
            'Mercredi' => 'Mercredi',
            'Jeudi' => 'Jeudi',
            'Vendredi' => 'Vendredi',
            'Samedi' => 'Samedi')
        , 'placeholder' => 'Ferme le'));
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Limitless\KarhabtiBundle\Entity\Agence'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'limitless_karhabtibundle_agence';
    }

  
}

src/Limitless/KarhabtiBundle/Controller/AgenceController.php
<?php

namespace Limitless\KarhabtiBundle\Controller;

use Limitless\KarhabtiBundle\Entity\Agence;
use Limitless\KarhabtiBundle\Entity\Commentaire;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Agence controller.
 *
 */
class AgenceController extends Controller
{
    /**
     * Lists all agence entities.
     *
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $user = $this->getUser();
        $agences = $em->getRepository('LimitlessKarhabtiBundle:Agence')->findBy(array('user' => $user));

        return $this->render('LimitlessKarhabtiBundle:agence:index.html.twig', array(
            'agences' => $agences,
        ));
    }

    /**
     * Creates a new agence entity.
     *
     */
    public function newAction(Request $request)
    {
        $agence = new Agence();
        $user = $this->getUser();
        $form = $this->createForm('Limitless\KarhabtiBundle\Form\AgenceType', $agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $image= $form['file']->getData();

            $req = $request->request->get('limitless_karhabtibundle_agence');
            $id=$req['nom'];
            if(!is_dir("bundles/limitlesskarhabti/Image/Agence")){
                mkdir("bundles/limitlesskarhabti/Image/Agence");

            }

            mkdir("bundles/limitlesskarhabti/Image/Vehicule/".$id);
            move_uploaded_file ($image,"bundles/limitlesskarhabti/Image/Agence/".$id."/".$image->getFileName());
            rename("bundles/limitlesskarhabti/Image/Agence/".$id."/".$image->getFileName(), "bundles/limitlesskarhabti/Image/Agence/".$id."/".$id.".jpg");



            $em = $this->getDoctrine()->getManager();
            $agence->setUser($user);

            $em->persist($agence);
            $em->flush();

            return $this->redirectToRoute('agence_show', array('id' => $agence->getId()));
        }


        return $this->render('LimitlessKarhabtiBundle:agence:new.html.twig', array(
            'agence' => $agence,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a agence entity.
     *
     */
    public function showAction(Agence $agence)
    {
        $deleteForm = $this->createDeleteForm($agence);


        return $this->render('LimitlessKarhabtiBundle:agence:show.html.twig', array(
            'agence' => $agence,
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Displays a form to edit an existing agence entity.
     *
     */
    public function editAction(Request $request, Agence $agence)
    {
        $deleteForm = $this->createDeleteForm($agence);
        $editForm = $this->createForm('Limitless\KarhabtiBundle\Form\AgenceType', $agence);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('agence_show', array('id' => $agence->getId()));
        }

        return $this->render('LimitlessKarhabtiBundle:agence:edit.html.twig', array(
            'agence' => $agence,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    public function avisAction(Request $request, Agence $agence)
    {

        $avisForm = $this->createForm('Limitless\KarhabtiBundle\Form\AvisForm', $agence);
        $avisForm->handleRequest($request);
        $old = $agence->getAvis();


        if ($avisForm->isSubmitted() && $avisForm->isValid()) {
            $new = $agence->getnewAvis();

            $avis = $old + $new;

            $agence->setAvis($avis);

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('agence_show', array('id' => $agence->getId()));
        }

        return $this->render('LimitlessKarhabtiBundle:agence:avis.html.twig', array(
            'edit_form' => $agence,
            'edit_form' => $avisForm->createView(),
            'agence' => $agence,


        ));
    }

    /**
     * Deletes a agence entity.
     *
     */
    public function deleteAction(Request $request, Agence $agence)
    {
        $form = $this->createDeleteForm($agence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($agence);
            $em->flush($agence);
        }

        return $this->redirectToRoute('agence_index');
    }

    /**
     * Creates a form to delete a agence entity.
     *
     * @param Agence $agence The agence entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm(Agence $agence)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('agence_delete', array('id' => $agence->getId())))
            ->setMethod('DELETE')
            ->getForm();
    }

    public function chartAction()
    {
        $em = $this->container->get('doctrine')->getEntityManager();
        $Agence = $em->getRepository('LimitlessKarhabtiBundle:Agence') > findAll();
        $categories = array();
        $avis = array();
        foreach ($Agence as $agence) {
            array_push($nom, $agence->getNom());
            array_push($avis, $agence->getAvis());
        }
        $series = array(array('name' => 'Agence', 'type' => 'column', 'color' => '#4572A7', 'yAxis' => 0, 'data' => $avis,));
        $yData = array(array('labels' => array('agence' => new Expr('function () { return this.value + "" }'), 'style' => array('color' => '#4572A7')), 'gridLineWidth' => 0, 'title' => array('text' => 'Nombre dávis', 'style' => array('color' => '#4572A7')),),);
        $ob = new Highchart();
        $ob->chart->renderTo('container'); // The #id of the div where to render the chart
        $ob->chart->type('column');
        $ob->title->text('Nombre dàvis par agence');
        $ob->xAxis->categories($categories);
        $ob->yAxis($yData);
        $ob->legend->enabled(false);
        $formatter = new Expr('function ()
 { var unit = {"agence": "agence(s)", }[this.series.name];
 return this.x + ": <b>" + this.y + "</b> " + unit;}');
        $ob->tooltip->agence($agence);
        $ob->series($series);
        return $this > render('LimitlessKarhabtiBundle:Graphe:chart.html.twig', array('chart' => $ob));
    }
}

src/Limitless/KarhabtiBundle/Resources/views/agence/avis.html.twig
{% extends 'LimitlessKarhabtiBundle:agence:index.html.twig' %}

{% block body %}
    <div class="row">
    <div class="blog-wrapper float-right col-md-8 col-xs-12">
        <div class="single-blog">
            <div class="blog-image">
                <img src=" {{asset('uploads/files/' ~  agence.image.file)}}" alt="" />
            </div>

            <div class="blog-meta fix">
                {{ form_start(edit_form) }}
                {{ form_widget(edit_form) }}
                <input  type="submit" value="envoyer" />
                {{ form_end(edit_form) }}
            </div>

        </div>
        <!-- Comments -->

        <!-- Comment Form -->

    </div>



{% endblock %}

src/Limitless/KarhabtiBundle/Resources/views/agence/edit.html.twig
{% extends 'LimitlessKarhabtiBundle:agence:index.html.twig' %}

{% block title_page %}Nouvelle Agence{% endblock %}
{% block text_page %} <a   href="{{ path('agence_index') }}">Liste des agences</a>{% endblock %}
{% block body %}

<div class="contact-form form text-left col-md-8 col-sm-7 col-xs-12"style="width: 100%">
    <style type="text/css">
        button {
            background-color: #dec839; /* Green */
            border: 1px solid #dec839;
            color: white;
            padding: 0px 0px;
            text-align: center;
            text-decoration: none;
            font-size: 16px;
            display: inline-block;
            width: auto;
            line-height: 30px;
        }
    </style>

    </br>
    <div>

        {{ form_start(edit_form) }}


        <div class="input-2">
            <div class="input">
                {{ form_widget(edit_form.nom,{'attr':{'placeholder':'Nom'}}) }}
            </div>
            <div class="input">
                {{ form_widget(edit_form.ville,{'attr':{'placeholder':'ville'}}) }}
            </div>
            <div class="input">
                {{ form_widget(edit_form.adresse,{'attr':{'placeholder':'adresse', 'class': 'limitless_karhabtibundle_agence_code_postal'} }) }}
            </div>
            <div class="input">
                {{ form_widget(edit_form.code_postal,{'attr':{'placeholder':'code postal'}}) }}
            </div>
            <div class="input">
                {{ form_widget(edit_form.telephone,{'attr':{'placeholder':'Telephone'}}) }}
            </div>
            <div class="input">
                {{ form_widget(edit_form.num_fiscal,{'attr':{'placeholder':'numero fiscal'}}) }}
            </div>
            <div class="input">
                {{ form_widget(edit_form.image,{'attr':{'placeholder':'image'}}) }}
            </div>
            <div class="input">
                {{ form_widget(edit_form.Ouverture,{'attr':{'placeholder':'ouverture'}}) }}
            </div>
            <div class="input">
                {{ form_widget(edit_form.Fermeture,{'attr':{'placeholder':'fermuture'}}) }}
            </div>

        </div>



        <div class="input input-submit"><input type="submit" value="sauvgarder" /></div>


        {{ form_end(edit_form) }}
        {{ form_start(delete_form) }}
        <div class="input input-submit" style="    float: right;margin-right: 250px;"><input type="submit" value="supprimer" /></div>
        {{ form_end(delete_form) }}
        <p class="form-messege"></p>
    </div>



{% endblock %}

src/Limitless/KarhabtiBundle/Resources/views/agence/index.html.twig
{% extends "LimitlessKarhabtiBundle::layout.html.twig" %}
{% block title %}
    {{ parent() }}
{% endblock %}
{% block body %}

    <!-- Header 1
 ============================================ -->
    <div class="header-area header-absolute header-transparent">
        <div class="header-bottom-2 sticky">
            <div class="container">
                <div class="row">
                    <!-- Header Bottom -->
                    <div class="col-xs-12">
                        <div class="navbar-header">
                            <a href="{{ path('limitless_karhabti_homepage') }}" class="logo navbar-brand"><img
                                        id="logo_img"
                                        src="{{ asset('bundles/limitlesskarhabti/img/logo/color-1.png') }}" alt="logo"/></a>
                        </div>
                        <div class="main-menu menu-style-6 mean-menu float-right">
                            <nav>
                                <ul>
                                    <li><a href="{{ path('limitless_karhabti_homepage') }}">home</a></li>
                                    <li><a href="#">Profil</a></li>
                                    <li><a href="#">Offre/Pack<i class="icofont icofont-simple-down"></i></a>
                                        <ul>
                                            <li><a href="{{ path('responsable_offre_index') }}">Offre</a></li>
                                            <li><a href="{{ path('responsable_pack_index') }}">Pack</a></li>
                                        </ul>
                                    </li>
                                    <li class="active"><a href="{{ path('responsable_vehicule_index') }}">Vehicule</a>
                                    </li>
                                    <li><a href="#">Moniteur</a></li>
                                    <li><a href="{{ path('reponsable_tache_index') }}">Planning</a></li>
                                    <li><a href="#">Cour/Examen<i class="icofont icofont-simple-down"></i></a>
                                        <ul>
                                            <li><a href="{{ path('responsable_cours_List') }}">Cour</a></li>
                                            <li><a href="{{ path('responsable_examen_Liste') }}">Examen</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="{{ path('limitless_karhabti_mail') }}">contact</a></li>
                                </ul>
                            </nav>
                        </div>
                        <div class="mobile-menu"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Banner -->
    <div class="page-banner-area overlay overlay-black overlay-70">
        <div class="container">
            <div class="row">
                <div class="page-banner text-center col-xs-12">
                    <h1>Responsable Auto école</h1>

                </div>
            </div>
        </div>
    </div>

    <div class="blog-area bg-white pt-90 pb-90">
        <div class="container">
            <!-- Section Title -->
            <div class="row">
                <div class="section-title text-center col-xs-12 mb-45">
                    <h3 class="heading">Liste des agences</h3>

                    <i class="icofont icofont-traffic-light"></i>
                </div>
            </div>
            <div class="row">
                <style type="text/css">
                    /*Table Style - This is what you want*/
                    button {
                        background-color: #dec839; /* Green */
                        border: 1px solid #dec839;
                        color: white;
                        padding: 0px 0px;
                        text-align: center;
                        text-decoration: none;
                        font-size: 16px;
                        display: inline-block;
                        width: auto;
                        line-height: 30px;
                    }

                </style>

                <ul>
                    <li style="text-align: center">
                        <button><a class="btn color " href="{{ path('agence_new') }}">créer une nouvelle agence</a>
                        </button>
                    </li>
                </ul>

                <br>
                {% set agen = 0 %}

                {% for agence in agences %}
                    {% set agen = agen + 1 %}
                {% endfor %}
                {% if agen==1 %}
                        <div align="center" class="image fix"><img
                                    src="{{ asset('bundles/limitlesskarhabti/img/testimonial/1.jpg') }}"
                                    alt=""/><br>
                        </div><br>

                    <div id="testimonial-area"
                         class=" text-center">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2 col-xs-12">
                                    <!-- Testimonial Image Slider -->
                                    <div class="ti-slider mb-40">

                                    </div>
                                    <!-- Testimonial Content Slider -->
                                    <div class="tc-slider">
                                        {% for agence in agences %}
                                            <div class="single-slide">
                                                <p>Cette agence est située à {{ agence.ville }}, {{ agence.adresse }}.
                                                    Elle
                                                    ouvre
                                                    "{{ agence.ouverture }}",
                                                    et elle ferme "{{ agence.fermeture }}", son num
                                                    fiscale {{ agence.numFiscal }}
                                                    .</p>
                                                <h5>{{ agence.nom }}</h5>
                                                <span>(+216) {{ agence.telephone }}</span>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div id="testimonial-area" class=" text-center ">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-8 col-md-offset-2 col-xs-12">
                                    <!-- Testimonial Image Slider -->
                                    <div class="ti-slider mb-40">
                                        {% for agence in agences %}
                                            <div class="single-slide">
                                                <div class="image fix"><img
                                                            src="{{ asset('bundles/limitlesskarhabti/img/testimonial/1.jpg') }}"
                                                            alt=""/></div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                    <!-- Testimonial Content Slider -->
                                    <div class="tc-slider">
                                        {% for agence in agences %}
                                            <div class="single-slide">
                                                <p>Cette agence est située à {{ agence.ville }}, {{ agence.adresse }}.
                                                    Elle
                                                    ouvre
                                                    "{{ agence.ouverture }}",
                                                    et elle ferme "{{ agence.fermeture }}", son num
                                                    fiscale {{ agence.numFiscal }}
                                                    .</p>
                                                <h5>{{ agence.nom }}</h5>
                                                <span>(+216) {{ agence.telephone }}</span>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}


            </div>

        </div>
    </div>
{% endblock %}

src/Limitless/KarhabtiBundle/Resources/views/agence/show.html.twig
{% extends 'LimitlessKarhabtiBundle:agence:index.html.twig' %}
{% block title_page %}{{ agence.nom }}{% endblock %}
{% block text_page %} <a class="btn color" href="{{ path('agence_index') }}">Liste des agences</a>{% endblock %}

{% block body %}

<div class="row">
    <div class="blog-wrapper float-right col-md-8 col-xs-12">
        <div class="single-blog">


            <div class="blog-meta fix">
           <p class="float-left"><a href="{{ path('agence_avis', {'id': agence.id}) }}"><i class="icofont icofont-speech-comments"></i>Voter </a> </p>

                <p class="float-right">

                    <a href="#"><i class="icofont icofont-speech-comments"></i> 42 comments</a>
                </p>
            </div>

        </div>
        <!-- Comments -->

        <!-- Comment Form -->

    </div>
    <div class="sidebar col-md-4 col-xs-12">
        <div class="single-sidebar">
            <h5 class="sidebar-title">{{ agence.nom }}</h5>
            <div class="about-sidebar">
                <p>Ouverte de  {{  agence.Ouverture }} a {{ agence.Fermeture }}.</p>
            </div>
        </div>
        <div class="single-sidebar">
            <h5 class="sidebar-title">Infos :</h5>
            <div class="category-sidebar">
                <ul>
                    <li>Ville: {{ agence.ville }}</li>
                    <li>Adresse: {{ agence.adresse }}</li>
                    <li>code postale: {{ agence.codePostal }}</li>
                    <li>Num telephone: {{ agence.telephone }}</li>
                    <li>Num fiscal: {{ agence.numFiscal }}</li>
                  {% if is_granted('ROLE_ADMIN') %}
                    <li><button style="margin-bottom: 20px;margin-left: 20px;width: 46%;"><a class="btn color" href="{{ path('agence_edit', { 'id': agence.id }) }}">Modifier</a></button></li>
                    <li> {{ form_start(delete_form) }}
                 <button style="margin-bottom: 20px;margin-left: 20px;width: 46%;"><input class="btn color" type="submit" value="supprimer" /></button>
            {{ form_end(delete_form) }}</li>
            {% endif %}

                </ul>
            </div>
        </div>


        </div>
    </div>
</div>
{% endblock %}

src/Limitless/KarhabtiBundle/Resources/views/agence/upload.html.twig
{% extends 'LimitlessKarhabtiBundle::layout.html.twig' %}

{% block slide %}
{#{{form(form)}}#}
<h1>Uploading cours</h1>
<div class="col-lg-4">
    {{ form_start(form) }}
    {# ... #}
    {{ form_row(form.contenue) }}
    {{ form_end(form) }}
</div>

{% endblock %}